In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv("car_prices.csv")
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850


In [3]:
p = 53
value = np.percentile(df["price"], p)
value

np.float64(29500.0)

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[3]

np.int64(4)

In [5]:
arr = np.random.randint(1, 10, (8, 8))
arr

array([[9, 9, 2, 1, 1, 8, 9, 7],
       [6, 6, 8, 6, 6, 7, 2, 9],
       [3, 9, 8, 5, 2, 3, 4, 8],
       [9, 4, 1, 5, 4, 2, 9, 2],
       [6, 5, 2, 7, 3, 7, 2, 3],
       [5, 4, 6, 4, 8, 7, 8, 5],
       [4, 4, 9, 5, 5, 2, 5, 2],
       [7, 2, 6, 8, 7, 8, 4, 7]], dtype=int32)

In [6]:
arr[3:6, 3:6]

array([[5, 4, 2],
       [7, 3, 7],
       [4, 8, 7]], dtype=int32)

In [7]:
arr[3:6:2, 3:6:2]

array([[5, 2],
       [4, 7]], dtype=int32)

In [9]:
arr.sort()
arr

array([[1, 1, 2, 7, 8, 9, 9, 9],
       [2, 6, 6, 6, 6, 7, 8, 9],
       [2, 3, 3, 4, 5, 8, 8, 9],
       [1, 2, 2, 4, 4, 5, 9, 9],
       [2, 2, 3, 3, 5, 6, 7, 7],
       [4, 4, 5, 5, 6, 7, 8, 8],
       [2, 2, 4, 4, 5, 5, 5, 9],
       [2, 4, 6, 7, 7, 7, 8, 8]], dtype=int32)

In [ ]:
np.sort(arr, axis = 0) # ustun boyicha 

array([[1, 1, 2, 3, 4, 5, 5, 7],
       [1, 2, 2, 4, 5, 5, 7, 8],
       [2, 2, 3, 4, 5, 6, 8, 8],
       [2, 2, 3, 4, 5, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 4, 5, 6, 6, 7, 8, 9],
       [2, 4, 6, 7, 7, 8, 9, 9],
       [4, 6, 6, 7, 8, 9, 9, 9]], dtype=int32)

In [15]:
arr = np.array([[0, 5, 1],
                [0, 2, 0],
                [1, 1, 2],
                [2, 2, 1],
                [0, 0, 0]])

np.sum(arr, axis = 0)

array([ 3, 10,  4])