In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([2, 4, 6, 8, 10])
arr[3]

np.int64(8)

In [4]:
arr_2D = np.random.randint(0, 9, (9, 9))
arr_2D

array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
       [3, 8, 3, 3, 6, 3, 0, 3, 2],
       [4, 8, 3, 5, 3, 4, 3, 5, 3],
       [7, 8, 8, 6, 5, 5, 3, 5, 1],
       [3, 5, 2, 0, 4, 2, 7, 1, 4],
       [5, 4, 0, 5, 3, 7, 3, 8, 1],
       [5, 7, 1, 6, 4, 4, 6, 2, 8],
       [3, 8, 6, 6, 4, 4, 0, 4, 6],
       [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32)

In [5]:
arr_2D[2, 4]

np.int32(3)

In [6]:
arr_2D[0]

array([5, 0, 6, 6, 7, 5, 8, 2, 7], dtype=int32)

In [9]:
arr_2D[:, 0]

array([5, 3, 4, 7, 3, 5, 5, 3, 4], dtype=int32)

In [10]:
arr_2D[:, 3]

array([6, 3, 5, 6, 0, 5, 6, 6, 0], dtype=int32)

In [11]:
arr[2: 4]

array([6, 8])

In [12]:
arr_2D

array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
       [3, 8, 3, 3, 6, 3, 0, 3, 2],
       [4, 8, 3, 5, 3, 4, 3, 5, 3],
       [7, 8, 8, 6, 5, 5, 3, 5, 1],
       [3, 5, 2, 0, 4, 2, 7, 1, 4],
       [5, 4, 0, 5, 3, 7, 3, 8, 1],
       [5, 7, 1, 6, 4, 4, 6, 2, 8],
       [3, 8, 6, 6, 4, 4, 0, 4, 6],
       [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32)

In [13]:
arr_2D[3:6, 3:6]

array([[6, 5, 5],
       [0, 4, 2],
       [5, 3, 7]], dtype=int32)

In [14]:
arr_2D[3:6:2, 3:6:2]

array([[6, 5],
       [5, 7]], dtype=int32)

In [16]:
np.sort(arr_2D)

array([[0, 2, 5, 5, 6, 6, 7, 7, 8],
       [0, 2, 3, 3, 3, 3, 3, 6, 8],
       [3, 3, 3, 3, 4, 4, 5, 5, 8],
       [1, 3, 5, 5, 5, 6, 7, 8, 8],
       [0, 1, 2, 2, 3, 4, 4, 5, 7],
       [0, 1, 3, 3, 4, 5, 5, 7, 8],
       [1, 2, 4, 4, 5, 6, 6, 7, 8],
       [0, 3, 4, 4, 4, 6, 6, 6, 8],
       [0, 0, 0, 2, 3, 4, 4, 4, 5]], dtype=int32)

In [20]:
np.sort(arr_2D, axis = 0)

array([[3, 0, 0, 0, 0, 2, 0, 1, 1],
       [3, 4, 1, 0, 3, 3, 0, 2, 1],
       [3, 4, 2, 3, 3, 4, 0, 2, 2],
       [4, 5, 2, 5, 4, 4, 3, 3, 3],
       [4, 7, 3, 5, 4, 4, 3, 3, 4],
       [5, 8, 3, 6, 4, 4, 3, 4, 5],
       [5, 8, 6, 6, 5, 5, 6, 5, 6],
       [5, 8, 6, 6, 6, 5, 7, 5, 7],
       [7, 8, 8, 6, 7, 7, 8, 8, 8]], dtype=int32)

In [21]:
arr_2D

array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
       [3, 8, 3, 3, 6, 3, 0, 3, 2],
       [4, 8, 3, 5, 3, 4, 3, 5, 3],
       [7, 8, 8, 6, 5, 5, 3, 5, 1],
       [3, 5, 2, 0, 4, 2, 7, 1, 4],
       [5, 4, 0, 5, 3, 7, 3, 8, 1],
       [5, 7, 1, 6, 4, 4, 6, 2, 8],
       [3, 8, 6, 6, 4, 4, 0, 4, 6],
       [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32)

In [23]:
arr_2D % 2 == 0

array([[False,  True,  True,  True, False, False,  True,  True, False],
       [False,  True, False, False,  True, False,  True, False,  True],
       [ True,  True, False, False, False,  True, False, False, False],
       [False,  True,  True,  True, False, False, False, False, False],
       [False, False,  True,  True,  True,  True, False, False,  True],
       [False,  True,  True, False, False, False, False,  True, False],
       [False, False, False,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False, False]])

In [25]:
arr_2D % 2

array([[1, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 1, 0, 1, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int32)

In [30]:
arr = np.arange(1, 6) % 2 == 0
arr

array([False,  True, False,  True, False])

In [36]:
arr[arr] % 2 

array([1, 1])

In [38]:
x_2 = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
x_2

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [ ]:
y_2 = np.array([[1, 22],
                [2, 23],
                [3, 27],
                [4, 26]])    # x_2 == y_2
y_2

array([[ 1, 22],
       [ 2, 23],
       [ 3, 27],
       [ 4, 26]])

In [42]:
x_1 = np.array([1, 22, 2, 21, 3, 27, 4, 26])
x_1

array([ 1, 22,  2, 21,  3, 27,  4, 26])

In [ ]:
y_1 = np.array([1, 22,
                2, 21,
                3, 27,   
                4, 26])   # x_1 == y_1
y_1

array([ 1, 22,  2, 21,  3, 27,  4, 26])

In [46]:
x_2

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [45]:
x_2[:, 0][x_2[:, 1] % 2 == 0]

array([1, 4])

In [47]:
x_2 

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [ ]:
np.where(x_2[:, 1] % 2 == 0) # np.where --> shart boyicah topadi yoki indeks topish funksiyasi

(array([0, 3]),)

In [51]:
np.where(arr_2D > 6, arr_2D, 0)

array([[0, 0, 0, 0, 7, 0, 8, 0, 7],
       [0, 8, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0],
       [7, 8, 8, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 7, 0, 8, 0],
       [0, 7, 0, 0, 0, 0, 0, 0, 8],
       [0, 8, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [53]:
arr_2D

array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
       [3, 8, 3, 3, 6, 3, 0, 3, 2],
       [4, 8, 3, 5, 3, 4, 3, 5, 3],
       [7, 8, 8, 6, 5, 5, 3, 5, 1],
       [3, 5, 2, 0, 4, 2, 7, 1, 4],
       [5, 4, 0, 5, 3, 7, 3, 8, 1],
       [5, 7, 1, 6, 4, 4, 6, 2, 8],
       [3, 8, 6, 6, 4, 4, 0, 4, 6],
       [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32)

In [54]:
sudoku_game = np.array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
                        [0, 0, 5, 0, 0, 9, 0, 0, 1],
                        [0, 7, 0, 0, 6, 0, 0, 4, 3],
                        [0, 0, 6, 0, 0, 2, 0, 8, 7],
                        [1, 9, 0, 0, 0, 7, 4, 0, 0],
                        [0, 5, 0, 0, 8, 3, 0, 0, 0],
                        [6, 0, 0, 0, 0, 0, 1, 0, 5],
                        [0, 0, 3, 5, 0, 8, 6, 9, 0],
                        [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [55]:
row , col = np.where(sudoku_game == 0)
row, col

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
        8, 8]),
 array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
        3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
        7, 8]))

In [56]:
np.where(sudoku_game == 0, "", sudoku_game)

array([['', '', '4', '3', '', '', '2', '', '9'],
       ['', '', '5', '', '', '9', '', '', '1'],
       ['', '7', '', '', '6', '', '', '4', '3'],
       ['', '', '6', '', '', '2', '', '8', '7'],
       ['1', '9', '', '', '', '7', '4', '', ''],
       ['', '5', '', '', '8', '3', '', '', ''],
       ['6', '', '', '', '', '', '1', '', '5'],
       ['', '', '3', '5', '', '8', '6', '9', ''],
       ['', '4', '2', '9', '1', '', '3', '', '']], dtype='<U21')

In [57]:
arr_2D

array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
       [3, 8, 3, 3, 6, 3, 0, 3, 2],
       [4, 8, 3, 5, 3, 4, 3, 5, 3],
       [7, 8, 8, 6, 5, 5, 3, 5, 1],
       [3, 5, 2, 0, 4, 2, 7, 1, 4],
       [5, 4, 0, 5, 3, 7, 3, 8, 1],
       [5, 7, 1, 6, 4, 4, 6, 2, 8],
       [3, 8, 6, 6, 4, 4, 0, 4, 6],
       [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32)

In [58]:
np.where(arr_2D == 5)

(array([0, 0, 2, 2, 3, 3, 3, 4, 5, 5, 6, 8]),
 array([0, 5, 3, 7, 4, 5, 7, 1, 0, 3, 0, 8]))

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
np.concatenate((x, y), axis = 0) # qatorga birlashtiradi

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [ ]:
x2 = np.array([[1, 2],
              [3, 4],
              [5, 6]])
y2 = np.array([[1],
               [2],
               [3]])

np.concatenate((x2, y2), axis = 1) # ustunlarni birlashtiradi

array([[1, 2, 1],
       [3, 4, 2],
       [5, 6, 3]])

In [66]:
np.add(x, y)

array([6, 6, 6, 6, 6])

In [67]:
np.add(x2, y2)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr_2D


array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
       [3, 8, 3, 3, 6, 3, 0, 3, 2],
       [4, 8, 3, 5, 3, 4, 3, 5, 3],
       [7, 8, 8, 6, 5, 5, 3, 5, 1],
       [3, 5, 2, 0, 4, 2, 7, 1, 4],
       [5, 4, 0, 5, 3, 7, 3, 8, 1],
       [5, 7, 1, 6, 4, 4, 6, 2, 8],
       [3, 8, 6, 6, 4, 4, 0, 4, 6],
       [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32)

In [77]:
a = np.delete(arr_2D, 1, axis = 0)

arr_2D[1], "", a

(array([3, 8, 3, 3, 6, 3, 0, 3, 2], dtype=int32),
 '',
 array([[5, 0, 6, 6, 7, 5, 8, 2, 7],
        [4, 8, 3, 5, 3, 4, 3, 5, 3],
        [7, 8, 8, 6, 5, 5, 3, 5, 1],
        [3, 5, 2, 0, 4, 2, 7, 1, 4],
        [5, 4, 0, 5, 3, 7, 3, 8, 1],
        [5, 7, 1, 6, 4, 4, 6, 2, 8],
        [3, 8, 6, 6, 4, 4, 0, 4, 6],
        [4, 4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32))

In [82]:
b = np.delete(arr_2D, 1, axis = 1)

arr_2D[:,1], "", b

(array([0, 8, 8, 8, 5, 4, 7, 8, 4], dtype=int32),
 '',
 array([[5, 6, 6, 7, 5, 8, 2, 7],
        [3, 3, 3, 6, 3, 0, 3, 2],
        [4, 3, 5, 3, 4, 3, 5, 3],
        [7, 8, 6, 5, 5, 3, 5, 1],
        [3, 2, 0, 4, 2, 7, 1, 4],
        [5, 0, 5, 3, 7, 3, 8, 1],
        [5, 1, 6, 4, 4, 6, 2, 8],
        [3, 6, 6, 4, 4, 0, 4, 6],
        [4, 2, 0, 0, 4, 0, 3, 5]], dtype=int32))

In [ ]:
# np.where(),  np.concatenate(), np.delete(),
# np.rehsape(), np.shape(), np.sort(),
# axis = 1 -->col,  axis = 0 --> row 
# .sum(), .min(), .max(), mean(), .cumsum()